// Ported from ezcontract/includes/class-awp-pricing.php lines 16-59
// Enhanced with comprehensive product catalog from Excel and product type codes reference

// ─── Markets ─────────────────────────────────────────────────────────────

export const MARKETS = {
  SLC: { name: "Salt Lake City", glassTypes: ["LoE-366", "LoE-i89"] },
  OREM: { name: "Orem", glassTypes: ["LoE-366", "LoE-i89"] },
  PHOENIX: { name: "Phoenix", glassTypes: ["Quad LoE-452+"] },
  VANCOUVER: { name: "Vancouver", glassTypes: ["Low-E", "Low-E+"] },
} as const;

export type Market = keyof typeof MARKETS;

// ─── Product Catalog ───────────────────────────────────────────────────────

// Operations (X = Operable panel, O = Fixed panel, viewed from exterior)
export const OPERATIONS = {
  // Slider operations
  "XO": { description: "Left panel slides, right fixed" },
  "OX": { description: "Left panel fixed, right slides" },
  "XOO": { description: "Left slides, two fixed right" },
  "OOX": { description: "Two fixed left, right slides" },
  "OXO-L": { description: "Fixed left, center slides, fixed right (L-handed)" },
  "OXO-R": { description: "Fixed left, center slides, fixed right (R-handed)" },
  "XOX": { description: "Two operable sides, fixed center" },
  "XOX-o": { description: "Double vent operating" },
  "OXXO": { description: "Fixed ends, two center operate" },
  "XOXXOO": { description: "Four panel slider" },

  // Single Hung operations
  "SH": { description: "Single Hung (bottom operates)" },
  "SH-o": { description: "Single Hung Operating variant" },

  // Picture windows
  "N/A": { description: "Fixed unit (no operation)" },

  // Door operations
  "STD": { description: "Standard door operation" },
} as const;

export type Operation = keyof typeof OPERATIONS;

// Grid types
export const GRID_TYPES = {
  "STD GRID": { description: "Standard Grid", pricingModifier: 0 },
  "CNT GRID": { description: "Contoured Grid", pricingModifier: 0.01 },
  "KE Grid": { description: "KE Grid (Specialty/Shape)", pricingModifier: 0.02 },
} as const;

export type GridType = keyof typeof GRID_TYPES;

// Glass types
export const GLASS_TYPES = {
  "LoE-366": { description: "LoE-366 Glass", markets: ["SLC", "OREM"] },
  "LoE-i89": { description: "LoE-i89 Glass", markets: ["SLC", "OREM"] },
  "Quad LoE-452+": { description: "Quad LoE-452+ Glass", markets: ["PHOENIX"] },
  "Low-E": { description: "Low-E Glass", markets: ["VANCOUVER"] },
  "Low-E+": { description: "Low-E+ Glass", markets: ["VANCOUVER"] },
  "STD": { description: "Standard Glass", markets: ["SLC", "OREM", "PHOENIX", "VANCOUVER"] },
} as const;

export type GlassType = keyof typeof GLASS_TYPES;

// Color options by market
export const COLORS_BY_MARKET = {
  SLC: {
    exterior: ["White", "Light Tan", "Dark Tan", "Black", "Bronze"],
    interior: ["White", "Light Tan", "Dark Tan"],
  },
  OREM: {
    exterior: ["White", "Light Tan", "Dark Tan", "Black", "Bronze"],
    interior: ["White", "Light Tan", "Dark Tan"],
  },
  PHOENIX: {
    exterior: ["White", "Light Tan", "Dark Tan"],
    interior: ["White", "Light Tan", "Dark Tan"],
  },
  VANCOUVER: {
    exterior: ["White", "Light Tan", "Dark Tan", "Eclipse (Black on Black)"],
    interior: ["White", "Light Tan", "Dark Tan"],
  },
} as const;

// Add-on options
export const ADD_ONS = {
  glass: {
    OBS: { label: "Obscured Glass", pricingModifier: 0.01 },
    TEMP: { label: "Tempered Glass", pricingModifier: 0.01 },
  },
  grids: {
    "STD GRID": { label: "Standard Grid", pricingModifier: 0 },
    "CNT GRID": { label: "Contoured Grid", pricingModifier: 0.01 },
    "KE Grid": { label: "KE Grid", pricingModifier: 0.02 },
  },
  colors: {
    LT: { label: "Light Tan", pricingModifier: 0 },
    DT: { label: "Dark Tan", pricingModifier: 0 },
    "Black": { label: "Black", pricingModifier: 0 },
    "Bronze": { label: "Bronze", pricingModifier: 0 },
    "Eclipse": { label: "Eclipse (Black on Black)", pricingModifier: 0 },
    "Color Match": { label: "Color Match", pricingModifier: 0 },
  },
  doors: {
    "Dog Door Add On": { label: "Dog Door Add On", pricingModifier: 0.05 },
  },
  phoenix: {
    "Lead Test Fees": { label: "Lead Test Fees", pricingModifier: 0 },
    "Lead Safe Installation": { label: "Lead Safe Installation", pricingModifier: 0 },
    "Window Wraps": { label: "Window Wraps", pricingModifier: 0.01 },
    "Door Wraps": { label: "Door Wraps", pricingModifier: 0.01 },
    "Storm Shutter Removal": { label: "Storm Shutter Removal", pricingModifier: 0.02 },
  },
} as const;

// ─── Products by Market ────────────────────────────────────────────────────

// Product definition interface
interface ProductDef {
  code: string;
  shortCode?: string;
  name: string;
  series: string;
  function: string;
  type: "Window" | "Door";
  markets: Market[];
  operations: Operation[];
  grids: GridType[];
  glassTypes: GlassType[];
  pricingModifier?: number;
}

// Patriot Series (SLC, OREM, PHOENIX)
const PATRIOT_PRODUCTS: ProductDef[] = [
  // Standard Windows
  {
    code: "Patriot SS",
    shortCode: "P SL",
    name: "Patriot Single Slider",
    series: "Patriot",
    function: "Single Slider",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
  },
  {
    code: "Patriot HP SS",
    shortCode: "HPSL",
    name: "Patriot High Performance Single Slider",
    series: "High Performance",
    function: "Single Slider",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  {
    code: "Patriot SH",
    shortCode: "P SH",
    name: "Patriot Single Hung",
    series: "Patriot",
    function: "Single Hung",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
  },
  {
    code: "Patriot HP SH",
    shortCode: "HPSH",
    name: "Patriot High Performance Single Hung",
    series: "High Performance",
    function: "Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  {
    code: "Patriot DV",
    shortCode: "P DV",
    name: "Patriot Double Vent",
    series: "Patriot",
    function: "Double Vent",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
  },
  {
    code: "Patriot HP DV",
    shortCode: "HPDV",
    name: "Patriot High Performance Double Vent",
    series: "High Performance",
    function: "Double Vent",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  {
    code: "Patriot PW",
    shortCode: "P PW",
    name: "Patriot Picture Window",
    series: "Patriot",
    function: "Picture",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
  },
  {
    code: "Patriot HP PW",
    shortCode: "HPPW",
    name: "Patriot High Performance Picture Window",
    series: "High Performance",
    function: "Picture",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  // Shapes/Specialty
  {
    code: "Patriot RT",
    shortCode: "RT",
    name: "Patriot Right Triangle (L/R)",
    series: "Patriot",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP RT",
    shortCode: "HP RT",
    name: "High Performance Right Triangle (L/R)",
    series: "High Performance",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ET",
    shortCode: "ET",
    name: "Patriot Equilateral Triangle",
    series: "Patriot",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ET",
    shortCode: "HP ET",
    name: "High Performance Equilateral Triangle",
    series: "High Performance",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot IT",
    shortCode: "IT",
    name: "Patriot Isosceles Triangle",
    series: "Patriot",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP IT",
    shortCode: "HP IT",
    name: "High Performance Isosceles Triangle",
    series: "High Performance",
    function: "Triangle",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot CIR",
    shortCode: "CIR",
    name: "Patriot Circle",
    series: "Patriot",
    function: "Circle",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP CIR",
    shortCode: "HP CIR",
    name: "High Performance Circle",
    series: "High Performance",
    function: "Circle",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot PENT",
    shortCode: "PENT",
    name: "Patriot Pentagon (L/R)",
    series: "Patriot",
    function: "Pentagon",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP PENT",
    shortCode: "HP PENT",
    name: "High Performance Pentagon (L/R)",
    series: "High Performance",
    function: "Pentagon",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot GP",
    shortCode: "GP",
    name: "Patriot Gable Pentagon",
    series: "Patriot",
    function: "Gable Pentagon",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP GP",
    shortCode: "HP GP",
    name: "High Performance Gable Pentagon",
    series: "High Performance",
    function: "Gable Pentagon",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot OCT",
    shortCode: "OCT",
    name: "Patriot Octagon",
    series: "Patriot",
    function: "Octagon",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP OCT",
    shortCode: "HP OCT",
    name: "High Performance Octagon",
    series: "High Performance",
    function: "Octagon",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot TRAP",
    shortCode: "TRAP",
    name: "Patriot Trapezoid (L/R)",
    series: "Patriot",
    function: "Trapezoid",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP TRAP",
    shortCode: "HP TRAP",
    name: "High Performance Trapezoid (L/R)",
    series: "High Performance",
    function: "Trapezoid",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot EB",
    shortCode: "EB",
    name: "Patriot Eyebrow",
    series: "Patriot",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP EB",
    shortCode: "HP EB",
    name: "High Performance Eyebrow",
    series: "High Performance",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ELEB",
    shortCode: "ELEB",
    name: "Patriot Extended Leg Eyebrow",
    series: "Patriot",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ELEB",
    shortCode: "HP ELEB",
    name: "High Performance Extended Leg Eyebrow",
    series: "High Performance",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot HEB",
    shortCode: "HEB",
    name: "Patriot Half Eyebrow (L/R)",
    series: "Patriot",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP HEB",
    shortCode: "HP HEB",
    name: "High Performance Half Eyebrow (L/R)",
    series: "High Performance",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ELHEB",
    shortCode: "ELHEB",
    name: "Patriot Extended Leg Half Eyebrow",
    series: "Patriot",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ELHEB",
    shortCode: "HP ELHEB",
    name: "High Performance Extended Leg Half Eyebrow",
    series: "High Performance",
    function: "Eyebrow",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot HR",
    shortCode: "HR",
    name: "Patriot Half Round",
    series: "Patriot",
    function: "Half Round",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP HR",
    shortCode: "HP HR",
    name: "High Performance Half Round",
    series: "High Performance",
    function: "Half Round",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ELHR",
    shortCode: "ELHR",
    name: "Patriot Extended Leg Half Round",
    series: "Patriot",
    function: "Half Round",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ELHR",
    shortCode: "HP ELHR",
    name: "High Performance Extended Leg Half Round",
    series: "High Performance",
    function: "Half Round",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot QR",
    shortCode: "QR",
    name: "Patriot Quarter Round (L/R)",
    series: "Patriot",
    function: "Quarter Round",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP QR",
    shortCode: "HP QR",
    name: "High Performance Quarter Round (L/R)",
    series: "High Performance",
    function: "Quarter Round",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ELQR",
    shortCode: "ELQR",
    name: "Patriot Extended Leg Quarter Round (L/R)",
    series: "Patriot",
    function: "Quarter Round",
    type: "Window",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ELQR",
    shortCode: "HP ELQR",
    name: "High Performance Extended Leg Quarter Round (L/R)",
    series: "High Performance",
    function: "Quarter Round",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot ATSH",
    shortCode: "ATSH",
    name: "Patriot Arch Top Single Hung",
    series: "Patriot",
    function: "Arch Top Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot HP ATSH",
    shortCode: "HP ATSH",
    name: "High Performance Arch Top Single Hung",
    series: "High Performance",
    function: "Arch Top Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  // Doors
  {
    code: "Patriot SGD",
    shortCode: "SGD",
    name: "Patriot Sliding Glass Door",
    series: "Patriot",
    function: "Sliding Door",
    type: "Door",
    markets: ["SLC", "OREM", "PHOENIX"],
    operations: ["XO", "OX", "XOO", "OOX", "OXO-L", "OXO-R", "OXXO"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89", "Quad LoE-452+"],
    pricingModifier: 0.05,
  },
];

// Signature/Autograph Series (VANCOUVER)
const VANCOUVER_PRODUCTS: ProductDef[] = [
  {
    code: "SIG SS",
    shortCode: "SIG SS",
    name: "Signature Single Slider",
    series: "Signature",
    function: "Single Slider",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0,
  },
  {
    code: "AG SS",
    shortCode: "AG SS",
    name: "Autograph Single Slider",
    series: "Autograph",
    function: "Single Slider",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.01,
  },
  {
    code: "SIG SH",
    shortCode: "SIG SH",
    name: "Signature Single Hung",
    series: "Signature",
    function: "Single Hung",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0,
  },
  {
    code: "AG SH",
    shortCode: "AG SH",
    name: "Autograph Single Hung",
    series: "Autograph",
    function: "Single Hung",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.01,
  },
  {
    code: "SIG DV",
    shortCode: "SIG DV",
    name: "Signature Double Vent",
    series: "Signature",
    function: "Double Vent",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0,
  },
  {
    code: "AG DV",
    shortCode: "AG DV",
    name: "Autograph Double Vent",
    series: "Autograph",
    function: "Double Vent",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.01,
  },
  {
    code: "SIG PW",
    shortCode: "SIG PW",
    name: "Signature Picture Window",
    series: "Signature",
    function: "Picture",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0,
  },
  {
    code: "AG PW",
    shortCode: "AG PW",
    name: "Autograph Picture Window",
    series: "Autograph",
    function: "Picture",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.01,
  },
  // Vancouver Shapes
  {
    code: "SIG RT",
    shortCode: "SIG RT",
    name: "Signature Right Triangle (L/R)",
    series: "Signature",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG RT",
    shortCode: "AG RT",
    name: "Autograph Right Triangle (L/R)",
    series: "Autograph",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG ET",
    shortCode: "SIG ET",
    name: "Signature Equilateral Triangle",
    series: "Signature",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG ET",
    shortCode: "AG ET",
    name: "Autograph Equilateral Triangle",
    series: "Autograph",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG IT",
    shortCode: "SIG IT",
    name: "Signature Isosceles Triangle",
    series: "Signature",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG IT",
    shortCode: "AG IT",
    name: "Autograph Isosceles Triangle",
    series: "Autograph",
    function: "Triangle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG CIR",
    shortCode: "SIG CIR",
    name: "Signature Circle",
    series: "Signature",
    function: "Circle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG CIR",
    shortCode: "AG CIR",
    name: "Autograph Circle",
    series: "Autograph",
    function: "Circle",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG PENT",
    shortCode: "SIG PENT",
    name: "Signature Pentagon (L/R)",
    series: "Signature",
    function: "Pentagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG PENT",
    shortCode: "AG PENT",
    name: "Autograph Pentagon (L/R)",
    series: "Autograph",
    function: "Pentagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG GP",
    shortCode: "SIG GP",
    name: "Signature Gable Pentagon",
    series: "Signature",
    function: "Gable Pentagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG GP",
    shortCode: "AG GP",
    name: "Autograph Gable Pentagon",
    series: "Autograph",
    function: "Gable Pentagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG OCT",
    shortCode: "SIG OCT",
    name: "Signature Octagon",
    series: "Signature",
    function: "Octagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG OCT",
    shortCode: "AG OCT",
    name: "Autograph Octagon",
    series: "Autograph",
    function: "Octagon",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG TRAP",
    shortCode: "SIG TRAP",
    name: "Signature Trapezoid (L/R)",
    series: "Signature",
    function: "Trapezoid",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG TRAP",
    shortCode: "AG TRAP",
    name: "Autograph Trapezoid (L/R)",
    series: "Autograph",
    function: "Trapezoid",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG EB",
    shortCode: "SIG EB",
    name: "Signature Eyebrow",
    series: "Signature",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG EB",
    shortCode: "AG EB",
    name: "Autograph Eyebrow",
    series: "Autograph",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG ELEB",
    shortCode: "SIG ELEB",
    name: "Signature Extended Leg Eyebrow",
    series: "Signature",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG ELEB",
    shortCode: "AG ELEB",
    name: "Autograph Extended Leg Eyebrow",
    series: "Autograph",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG HEB",
    shortCode: "SIG HEB",
    name: "Signature Half Eyebrow (L/R)",
    series: "Signature",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG HEB",
    shortCode: "AG HEB",
    name: "Autograph Half Eyebrow (L/R)",
    series: "Autograph",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG ELHEB",
    shortCode: "SIG ELHEB",
    name: "Signature Extended Leg Half Eyebrow",
    series: "Signature",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG ELHEB",
    shortCode: "AG ELHEB",
    name: "Autograph Extended Leg Half Eyebrow",
    series: "Autograph",
    function: "Eyebrow",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG HR",
    shortCode: "SIG HR",
    name: "Signature Half Round",
    series: "Signature",
    function: "Half Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG HR",
    shortCode: "AG HR",
    name: "Autograph Half Round",
    series: "Autograph",
    function: "Half Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG ELHR",
    shortCode: "SIG ELHR",
    name: "Signature Extended Leg Half Round",
    series: "Signature",
    function: "Half Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG ELHR",
    shortCode: "AG ELHR",
    name: "Autograph Extended Leg Half Round",
    series: "Autograph",
    function: "Half Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG QR",
    shortCode: "SIG QR",
    name: "Signature Quarter Round (L/R)",
    series: "Signature",
    function: "Quarter Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG QR",
    shortCode: "AG QR",
    name: "Autograph Quarter Round (L/R)",
    series: "Autograph",
    function: "Quarter Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG ELQR",
    shortCode: "SIG ELQR",
    name: "Signature Extended Leg Quarter Round (L/R)",
    series: "Signature",
    function: "Quarter Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.02,
  },
  {
    code: "AG ELQR",
    shortCode: "AG ELQR",
    name: "Autograph Extended Leg Quarter Round (L/R)",
    series: "Autograph",
    function: "Quarter Round",
    type: "Window",
    markets: ["VANCOUVER"],
    operations: ["N/A"],
    grids: ["KE Grid"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.03,
  },
  {
    code: "SIG SGD",
    shortCode: "SGD",
    name: "Signature Sliding Glass Door",
    series: "Signature",
    function: "Sliding Door",
    type: "Door",
    markets: ["VANCOUVER"],
    operations: ["XO", "OX", "XOO", "OOX", "OXO-L", "OXO-R", "OXXO"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["Low-E", "Low-E+"],
    pricingModifier: 0.05,
  },
];

// Sunview Series (from product type codes image - WHITE ONLY, No ARCH/EYEBROW)
const SUNVIEW_PRODUCTS: ProductDef[] = [
  {
    code: "Sunview SSL",
    shortCode: "SSL",
    name: "Sunview Horizontal Slider",
    series: "Sunview",
    function: "Slider",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: -0.02,
  },
  {
    code: "Sunview SSH",
    shortCode: "SSH",
    name: "Sunview Single Hung",
    series: "Sunview",
    function: "Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: -0.02,
  },
  {
    code: "Sunview SPW",
    shortCode: "SPW",
    name: "Sunview Picture Window",
    series: "Sunview",
    function: "Picture",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: -0.02,
  },
  {
    code: "Sunview SDV",
    shortCode: "SDV",
    name: "Sunview Double Vent",
    series: "Sunview",
    function: "Double Vent",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: -0.02,
  },
];

// Imperial Series (from product type codes image)
const IMPERIAL_PRODUCTS: ProductDef[] = [
  {
    code: "Imperial IC",
    shortCode: "IC",
    name: "Imperial Casement",
    series: "Imperial",
    function: "Casement",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Imperial ICP",
    shortCode: "ICP",
    name: "Imperial Casement Picture",
    series: "Imperial",
    function: "Picture",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Imperial IA",
    shortCode: "IA",
    name: "Imperial Awning",
    series: "Imperial",
    function: "Awning",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["N/A"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
];

// Legacy Doors (from product type codes image)
const LEGACY_DOORS: ProductDef[] = [
  {
    code: "Legacy SSD",
    shortCode: "SSD",
    name: "Single Swing Door",
    series: "Legacy",
    function: "Swing Door",
    type: "Door",
    markets: ["SLC", "OREM"],
    operations: ["STD"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.05,
  },
  {
    code: "Legacy ATD",
    shortCode: "ATD",
    name: "Atrium Door",
    series: "Legacy",
    function: "Swing Door",
    type: "Door",
    markets: ["SLC", "OREM"],
    operations: ["STD"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.06,
  },
  {
    code: "Legacy FRENCH",
    shortCode: "FRENCH",
    name: "French Door",
    series: "Legacy",
    function: "French Door",
    type: "Door",
    markets: ["SLC", "OREM"],
    operations: ["STD"],
    grids: ["STD GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.08,
  },
];

// Additional Patriot products from image (not in Excel)
const ADDITIONAL_PATRIOT_PRODUCTS: ProductDef[] = [
  {
    code: "Patriot DH",
    shortCode: "P DH",
    name: "Patriot Double Hung",
    series: "Patriot",
    function: "Double Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  {
    code: "Patriot DS",
    shortCode: "P DS",
    name: "Patriot Double Slider",
    series: "Patriot",
    function: "Double Slider",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XOX", "XOX-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.01,
  },
  {
    code: "Patriot V-P SL",
    shortCode: "V-P SL",
    name: "Variable Sash Slider",
    series: "Patriot",
    function: "Slider",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["XO", "OX"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.02,
  },
  {
    code: "Patriot O-P SH",
    shortCode: "O-P SH",
    name: "Oriol Single Hung",
    series: "Patriot",
    function: "Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.03,
  },
  {
    code: "Patriot V-P SH",
    shortCode: "V-P SH",
    name: "Variable Sash Single Hung",
    series: "Patriot",
    function: "Single Hung",
    type: "Window",
    markets: ["SLC", "OREM"],
    operations: ["SH", "SH-o"],
    grids: ["STD GRID", "CNT GRID"],
    glassTypes: ["LoE-366", "LoE-i89"],
    pricingModifier: 0.02,
  },
];

// Combine all products
export const PRODUCTS = {
  ...Object.fromEntries(
    [...PATRIOT_PRODUCTS, ...VANCOUVER_PRODUCTS, ...SUNVIEW_PRODUCTS, ...IMPERIAL_PRODUCTS, ...LEGACY_DOORS, ...ADDITIONAL_PATRIOT_PRODUCTS].map(
      (p) => [p.code, p]
    )
  ),
} as Record<string, ProductDef>;

// Get products by market
export function getProductsByMarket(market: Market): ProductDef[] {
  return Object.values(PRODUCTS).filter((p) => p.markets.includes(market));
}

// Get product by code
export function getProductByCode(code: string): ProductDef | undefined {
  return PRODUCTS[code];
}

// ─── Pricing ────────────────────────────────────────────────────────────────

export const PRICING = {
  baseRate: 0.55, // $ per square inch

  color: {
    White: 0,
    "Light Tan": 0,
    "Dark Tan": 0,
    Eclipse: 0.01,
    "Black Out White": 0,
    Bronze: 0,
    Black: 0,
    "Eclipse (Black on Black)": 0.01,
  } as Record<string, number>,

  series: {
    Patriot: 0,
    "High Performance": 0.01,
    Autograph: 0,
    Signature: 0.01,
    Sunview: -0.02,
    Imperial: 0.03,
    Legacy: 0.05,
  } as Record<string, number>,

  frame: {
    "Nail Fin": 0,
    "Flush Fin": 0,
    "Frame Over": -0.01,
  } as Record<string, number>,

  function: {
    Slider: 0,
    Picture: 0,
    Eyebrow: 0.02,
    Vent: 0.02,
    "Double Vent": 0.02,
    "Single Hung": 0,
    "Double Hung": 0.01,
    "Double Slider": 0.01,
    Casement: 0.03,
    Awning: 0.03,
    Triangle: 0.02,
    Circle: 0.02,
    Pentagon: 0.02,
    "Gable Pentagon": 0.02,
    Octagon: 0.02,
    Trapezoid: 0.02,
    "Half Round": 0.02,
    "Extended Leg Half Round": 0.02,
    "Quarter Round": 0.02,
    "Extended Leg Quarter Round": 0.02,
    "Arch Top Single Hung": 0.02,
  } as Record<string, number>,

  // New pricing modifiers
  operation: {
    "XO": 0,
    "OX": 0,
    "XOO": 0.01,
    "OOX": 0.01,
    "OXO-L": 0.02,
    "OXO-R": 0.02,
    "XOX": 0.02,
    "XOX-o": 0.02,
    "OXXO": 0.03,
    "XOXXOO": 0.04,
    "SH": 0,
    "SH-o": 0.01,
    "N/A": 0,
    "STD": 0,
  } as Record<string, number>,

  gridType: {
    "STD GRID": 0,
    "CNT GRID": 0.01,
    "KE Grid": 0.02,
  } as Record<string, number>,

  glassType: {
    "LoE-366": 0,
    "LoE-i89": 0.01,
    "Quad LoE-452+": 0.02,
    "Low-E": 0,
    "Low-E+": 0.01,
    "STD": 0,
  } as Record<string, number>,

  booleanAddons: {
    temperedGlass: 0.01,
    obscuredGlass: 0.01,
    customShape: 0.02,
    wrap: 0.01,
    coated: 0.01,
    awpShutterRnr: 0.02,
  } as Record<string, number>,
};

// ─── Form Options ───────────────────────────────────────────────────────────

export const FORM_OPTIONS = {
  type: ["Window", "Door"],

  color: ["White", "Light Tan", "Dark Tan", "Eclipse", "Black Out White", "Bronze", "Black"],

  series: ["Patriot", "High Performance", "Autograph", "Signature", "Sunview", "Imperial", "Legacy"],

  frame: ["Nail Fin", "Flush Fin", "Frame Over"],

  function: [
    "Slider",
    "Single Slider",
    "Double Slider",
    "Picture",
    "Eyebrow",
    "Single Hung",
    "Double Hung",
    "Vent",
    "Double Vent",
    "Casement",
    "Awning",
    "Triangle",
    "Circle",
    "Pentagon",
    "Gable Pentagon",
    "Octagon",
    "Trapezoid",
    "Half Round",
    "Extended Leg Half Round",
    "Quarter Round",
    "Extended Leg Quarter Round",
    "Arch Top Single Hung",
    "Swing Door",
    "French Door",
    "Sliding Door",
  ],

  operations: Object.keys(OPERATIONS),

  gridTypes: Object.keys(GRID_TYPES),

  glassTypes: Object.keys(GLASS_TYPES),

  houseType: ["Brick", "Siding", "Wood", "Stucco", "Foundation"],

  paymentMethod: [
    { value: "cash", label: "Cash" },
    { value: "check", label: "Check" },
    { value: "finance", label: "Finance" },
    { value: "credit_card", label: "Credit Card" },
    { value: "ach", label: "ACH" },
  ],

  marketingSource: [
    "TV",
    "Digital",
    "PC",
    "Magazine",
    "Radio",
    "Referral",
    "Other",
  ],

  addendumProductTypes: [
    "Double Hung Windows",
    "Slider Windows",
    "Casement Windows",
    "Awning Windows",
    "Picture Windows",
    "Bay Windows",
    "Bow Windows",
    "Garden Windows",
    "Hopper Windows",
    "Patio Doors",
    "Entry Doors",
    "Storm Doors",
    "Specialty Windows",
    "Skylights",
  ],

  interiorColors: [
    "White",
    "Light Tan",
    "Dark Tan",
    "Woodgrain",
    "Custom",
  ],

  exteriorColors: [
    "White",
    "Light Tan",
    "Dark Tan",
    "Bronze",
    "Black",
    "Custom",
  ],
};

// ─── Contract Statuses ──────────────────────────────────────────────────────

export const CONTRACT_STATUSES = {
  DRAFT: { label: "Draft", color: "secondary" },
  PENDING_SIGNATURE: { label: "Pending Signature", color: "highlight" },
  SIGNED: { label: "Signed", color: "outline" },
  COMPLETED: { label: "Completed", color: "success" },
} as const;

// ─── Boolean Add-on Labels ───────────────────────────────────────────────────

export const BOOLEAN_ADDON_LABELS: Record<string, string> = {
  temperedGlass: "Tempered",
  obscuredGlass: "Obscured",
  customShape: "Custom Shape",
  wrap: "Wrap",
  coated: "Coated",
  awpShutterRnr: "Shutter RNR",
};
